### ISSUE TITLE
Cake 4.3 Routing deprecation

### ISSUE THREAD

**Issue by raul338** [dereuromark/CakePHP-DatabaseLog#42]
This should be fixed by changing `config/routes.php`, and requiring cake 4.3

```diff
diff --git a/config/routes.php b/config/routes.php
index 6ed7cdd..0cd2bce 100644
--- a/config/routes.php
+++ b/config/routes.php
@@ -3,7 +3,8 @@
 use Cake\Routing\RouteBuilder;
 use Cake\Routing\Router;
 
-Router::prefix('Admin', function (RouteBuilder $routes) {
+/** @var \Cake\Routing\RouteBuilder $routes */
+$routes->prefix('Admin', function (RouteBuilder $routes) {
```

I tried to make a PR but couldn't get test to run with new Test Migrator

**Comment by dereuromark** [comment]
`@deprecated 4.3.0 Use the non-static method `RouterBuilder::prefix()` instead.`

This cannot be fixed in a way that it works for CakePHP 4.2 as well
As such you should just set
- `routes` to false for loading the plugin, and define the routes on app level for now.
- or silence all deprecations coming from plugins in vendor (as they are not relevant for your app deprecations and outside of control)
